spring:
  main:
    web-application-type: none
  cloud:
    stream:
      default:
        group: breathe
      bindings:
        processor-in-0:
          destination: breathe-requested
        processor-out-0:
          destination: breathe-completed
