spring:
  main:
    web-application-type: none
  cloud:
    function:
      definition: processor
    stream:
      default-binder: rabbit
      default:
        group: ${spring.application.name}
      bindings:
        processor-in-0:
          destination: ${spring.application.name}-requested
        processor-out-0:
          destination: ${spring.application.name}-completed

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: worker-${spring.application.name}
      instance: worker-${spring.application.name}-0
