spring:
  main:
    web-application-type: none
  cloud:
    function:
      definition: processor
    stream:
      default:
        group: ${spring.application.name}
      bindings:
        processor-in-0:
          destination: ${spring.application.name}-requested
        processor-out-0:
          destination: ${spring.application.name}-completed
