server:
  port: 8484

spring:
  application:
    name: api
  jackson:
    default-property-inclusion: non_null
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.geode.boot.autoconfigure.ClientCacheAutoConfiguration
  cloud:
    function:
      definition: moveCompleted;turnCompleted
    stream:
      default-binder: rabbit
      bindings:

        moveCompleted-in-0:
          destination: move-completed
        turnCompleted-in-0:
          destination: turn-completed


sla:
  millis: 2500
  timeout-millis: 5000

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      instance: ${spring.application.name}-0
