---
version: "3"
services:

  grafana:
    image: grafana/grafana:8.1.5-ubuntu
    container_name: grafana
    volumes:
      - "./provisioning:/etc/grafana/provisioning"
      - "./grafana.ini:/etc/grafana/grafana.ini"
    ports:
    - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.30.1
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  redis:
    image: redis:6.2.5-buster
    container_name: redis
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
