global:
  scrape_interval: 5s
  scrape_timeout: 1s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'boot-apps'
    metrics_path: '/actuator/prometheus'
    honor_labels: true
    static_configs:
      - targets: 
        - 'host.docker.internal:8484'
        - 'host.docker.internal:8585'
