server:
  port: 8585

spring:
  application:
    name: choreographer
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.geode.boot.autoconfigure.ClientCacheAutoConfiguration
  cloud:
    function:
      definition: breathe;act;react;think;move
    stream:
      default-binder: rabbit
      default:
        group: ${spring.application.name}
      bindings:

        breathe-in-0:
          destination: breathe-completed
        act-in-0:
          destination: act-completed
        react-in-0:
          destination: react-completed
        think-in-0:
          destination: think-completed
        move-in-0:
          destination: move-requested
        turn-in-0:
          destination: turn-completed

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      instance: ${spring.application.name}-0
