server:
  port: 8585

spring:
  application:
    name: choreographer
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfiguration
      - org.springframework.geode.boot.autoconfigure.ClientCacheAutoConfiguration
  cloud:
    function:
      definition: forward;back;right;left;move
    stream:
      default-binder: rabbit
      default:
        group: ${spring.application.name}
      bindings:

        forward-in-0:
          destination: forward-completed
        back-in-0:
          destination: back-completed
        right-in-0:
          destination: right-completed
        left-in-0:
          destination: left-completed
        move-in-0:
          destination: move-requested
        turn-in-0:
          destination: turn-completed

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      instance: ${spring.application.name}-0
